---
title       : "Benefit/Cost Analysis of Urban Trees"
subtitle    : 
author      : Monica Figueroa
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Slide 1
All over the world urban communities are growing faster than ever before.
Concerns with natural resources managements is increasing since quality of life depends on them.  
  
Urban green areas, and urban forest provide many ecosystem services such as runoff reduction, pollution reduction, carbon sequestration, energy savings among others.  
  
The cost of maintainig such areas is important but comparing the cost of maintenance with the economic value of ecosystem services one can see the importance of protect and construct green spaces in urban areas.


--- .class #id 

## Slide 2

This app intends to give you a gross estimate of the values of ecosystem services of urban trees and also the cost of mantaining them. Calculations are based on an article writen by Kane & Kirwan (2009). Estimates of runoff reduction, pollution reduction, carbon sequestration and energy savings by the trees are calculated with a linear function that uses the diameter at breast height (DBH)which is an estimate of tree maturity.  
  



--- .class #id 

## Slide 3
The values obtained are multipled by the number of trees. Costs used in this excercise are given in the article but the authors warns the readers that they might change, sometimes significantly, depending on a particular situation so these values should not be used except for the demonstration purposes.  
  
One of the things you learn using this app is the relatioship between the age of the trees and the magnitude of the value of ecosystem services in relation to the cost of maintenance.  
  
In the next graph we can see how the rate savings/cost changes with the age of the trees: 

--- .class #id 

## Slide 4
```{r, echo=FALSE}
library(ggplot2)
ratio<-data.frame(Size=c("Juvenile", "Young", "Mature"), Rate=c(0.3,1.306,1.97))

ggplot(ratio, aes(x = Size, y = Rate, fill = Size)) + geom_bar(stat = "identity")

```


--- .class #id 

## Slide 5
One of the thing you can conclude from this app is that the cost of creating and mantaining new green spaces with trees will be very high for the first ten years but later that area will return at least twice the money you invest in ecosystem services.  
  
If the city already have a urban forest is an investment to preserve it intact or try to make it bigger.
